Repository vas-dav/SHOH-Innovation-Project, pull requests merged in 2023-06, with the labels that each got.

#59 cleanup: delete blinky
  source/freertos_blinky/.cproject
  source/freertos_blinky/.gitignore
  source/freertos_blinky/.project
  source/freertos_blinky/.settings/language.settings.xml
  source/freertos_blinky/example/inc/FreeRTOSConfig.h
  source/freertos_blinky/example/src/aeabi_romdiv_patch.s
  source/freertos_blinky/example/src/cr_startup_lpc11u6x.c
  source/freertos_blinky/example/src/crp.c
  source/freertos_blinky/example/src/freertos_blinky.c
  source/freertos_blinky/example/src/mtb.c
  source/freertos_blinky/example/src/sysinit.c
  source/freertos_blinky/freertos/inc/FreeRTOS.h
  source/freertos_blinky/freertos/inc/StackMacros.h
  source/freertos_blinky/freertos/inc/croutine.h
  source/freertos_blinky/freertos/inc/list.h
  source/freertos_blinky/freertos/inc/mpu_wrappers.h
  source/freertos_blinky/freertos/inc/portable.h
  source/freertos_blinky/freertos/inc/portmacro.h
  source/freertos_blinky/freertos/inc/projdefs.h
  source/freertos_blinky/freertos/inc/queue.h
  source/freertos_blinky/freertos/inc/semphr.h
  source/freertos_blinky/freertos/inc/task.h
  source/freertos_blinky/freertos/inc/timers.h
  source/freertos_blinky/freertos/src/FreeRTOSCommonHooks.c
  source/freertos_blinky/freertos/src/FreeRTOSCommonHooks.h
  source/freertos_blinky/freertos/src/heap_3.c
  source/freertos_blinky/freertos/src/list.c
  source/freertos_blinky/freertos/src/port.c
  source/freertos_blinky/freertos/src/queue.c
  source/freertos_blinky/freertos/src/tasks.c
  source/freertos_blinky/readme.txt
Labels: enhancement

#63 threads: [#60] display error when temperature is unavailable
  source/shoh/src/threads/manager/Menu.cpp
  source/shoh/src/threads/manager/Menu.h
  source/shoh/src/threads/temperature/Temperature.cpp
Labels: bug

#66 Temperature
  source/shoh/src/threads/relay/Relay.h
  source/shoh/src/threads/rotary/Rotary.cpp
  source/shoh/src/threads/rotary/Rotary.h
  source/shoh/src/threads/temperature/SensorTempSHT20.cpp
  source/shoh/src/threads/temperature/SensorTempSHT20.h
  source/shoh/src/threads/temperature/Temperature.cpp
  source/shoh/src/threads/user_interface/UserInterface.cpp
Labels: bug, enhancement, Sensors, prototype
